export const booksData = [
    {
      workbookTags: ["자서전을 쓰고 싶어요."],
      isGif: false,
      image: "biography.jpeg",
      alt: "A book shaking",
    },
    {
      workbookTags: ["자서전을 쓰고 싶어요.", "내 감정을 알고 싶어요."],
      isGif: false,
      image: "card1.jpeg",
      alt: "A book shaking",
    },
    {
      workbookTags: ["자서전을 쓰고 싶어요."],
      isGif: false,
      image: "card2.jpeg",
      alt: "A book shaking",
    },
    {
      workbookTags: ["색칠하고 싶어요.", "꽃을 색칠하고 싶어요."],
      isGif: false,
      image: "coloring.png",
      alt: "A pencil drawing book",
    },
    {
      emotionTags: ["내 인생스토리를 만들고 싶어요.", "자서전을 쓰고 싶어요."],
      isGif: false,
      image: "life-story.jpeg",
      alt: "A book shaking",
    },
    {
      emotionTags: ["happy", "relaxed"],
      isGif: false,
      image: "happy.jpeg",
      alt: "A cat looking happy",
    },
    {
      emotionTags: ["hungry"],
      isGif: false,
      image: "hungry.jpeg",
      alt: "A cat looking hungry",
    },
    {
      emotionTags: ["hungry"],
      isGif: false,
      image: "hungry1.jpeg",
      alt: "A cat looking hungry",
    },
    {
      emotionTags: ["insomniac"],
      isGif: false,
      image: "insomnia.jpeg",
      alt: "A cat looking insomniac",
    },
    {
      emotionTags: ["insomniac"],
      isGif: false,
      image: "insomnia1.jpeg",
      alt: "A cat looking insomniac",
    },
    {
      emotionTags: ["relaxed"],
      isGif: false,
      image: "lazy.jpeg",
      alt: "A cat looking lazy",
    },
    {
      emotionTags: ["scared"],
      isGif: false,
      image: "nervous.jpeg",
      alt: "A cat looking nervous",
    },
    {
      emotionTags: ["sad"],
      isGif: false,
      image: "sad.jpeg",
      alt: "A cat looking sad",
    },
    {
      emotionTags: ["sad", "moody"],
      isGif: false,
      image: "sad1.jpeg",
      alt: "A cat looking sad",
    },
    {
      emotionTags: ["moody"],
      isGif: true,
      image: "angry.gif",
      alt: "A cat looking moody",
    },
    {
      emotionTags: ["moody"],
      isGif: true,
      image: "angry2.gif",
      alt: "A cat looking angry",
    },
    {
      emotionTags: ["confused"],
      isGif: true,
      image: "confused2.gif",
      alt: "A cat looking confused",
    },
    {
      emotionTags: ["dominant"],
      isGif: true,
      image: "dominant.gif",
      alt: "A cat looking dominant",
    },
    {
      emotionTags: ["happy"],
      isGif: true,
      image: "happy.gif",
      alt: "A cat looking happy",
    },
    {
      emotionTags: ["hungry", "sad", "confused"],
      isGif: true,
      image: "confused.gif",
      alt: "A cat looking hungry",
    },
    {
      emotionTags: ["hungry"],
      isGif: true,
      image: "hungry.gif",
      alt: "A cat looking hungry",
    },
    {
      emotionTags: ["hungry"],
      isGif: true,
      image: "hungry2.gif",
      alt: "A cat looking hungry",
    },
    {
      emotionTags: ["insomniac", "scared"],
      isGif: true,
      image: "insomnia2.gif",
      alt: "A cat looking insomniac",
    },
    {
      emotionTags: ["relaxed"],
      isGif: true,
      image: "lazy.gif",
      alt: "A cat looking relaxed",
    },
    {
      emotionTags: ["relaxed"],
      isGif: true,
      image: "relaxed2.gif",
      alt: "A cat looking relaxed",
    },
    {
      emotionTags: ["scared", "sad"],
      isGif: true,
      image: "nervous.gif",
      alt: "A cat looking nervous",
    },
    {
      emotionTags: ["scared"],
      isGif: true,
      image: "nervous2.gif",
      alt: "A cat looking scared",
    },
    {
      emotionTags: ["sad"],
      isGif: true,
      image: "sad.gif",
      alt: "A cat looking sad",
    },
  ];
  